import type { FC, SVGProps } from "react";

import {
  ArrowRight,
  BarChart3,
  Bell,
  Briefcase,
  Building2,
  Clock,
  Code2,
  DollarSign,
  Download,
  FileText,
  Filter,
  LayoutGrid,
  List,
  Monitor,
  MousePointerClick,
  Paperclip,
  Play,
  Plus,
  PlusCircle,
  Rocket,
  Search,
  Server,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Star,
  Table,
  Tag,
  Terminal,
  TrendingUp,
  Upload,
  Users,
  Zap,
} from "lucide-react";

/**
 * Icon registry for content (MDX) that references icons by string name.
 *
 * Keys are canonical lucide PascalCase component names. Content authors pick
 * from this set; consumers resolve via `ICONS[name]`. Keep the set as small as
 * actually used — this ships to the client.
 */
export const ICONS: Record<string, FC<SVGProps<SVGSVGElement>>> = {
  ArrowRight,
  BarChart3,
  Bell,
  Briefcase,
  Building2,
  Clock,
  Code2,
  DollarSign,
  Download,
  FileText,
  Filter,
  LayoutGrid,
  List,
  Monitor,
  MousePointerClick,
  Paperclip,
  Play,
  Plus,
  PlusCircle,
  Rocket,
  Search,
  Server,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Star,
  Table,
  Tag,
  Terminal,
  TrendingUp,
  Upload,
  Users,
  Zap,
};
